-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 14:46:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pharmacy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pharmacy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pharmacy` DEFAULT CHARACTER SET utf8 ;
USE `db_pharmacy` ;

-- -----------------------------------------------------
-- Table `db_pharmacy`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Role` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Role` (
  `Role_id` INT NOT NULL,
  `Role_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`User` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`User` (
  `User_id` INT NOT NULL,
  `User_name` VARCHAR(45) NOT NULL,
  `Email` NVARCHAR(50) NOT NULL,
  `Password` NVARCHAR(50) NOT NULL,
  `Role_id` INT NOT NULL,
  PRIMARY KEY (`User_id`),
  INDEX `Role_id_idx` (`Role_id` ASC) VISIBLE,
  CONSTRAINT `Role_id`
    FOREIGN KEY (`Role_id`)
    REFERENCES `db_pharmacy`.`Role` (`Role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Seller` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Seller` (
  `Seller_id` INT NOT NULL,
  `Seller_name` VARCHAR(45) NOT NULL,
  `Contact_no` INT NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Seller_id`),
  INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `User_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `db_pharmacy`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Supplier` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Supplier` (
  `Supplier_id` INT NOT NULL,
  `Supplier_name` VARCHAR(45) NOT NULL,
  `Contact_no` NVARCHAR(50) NOT NULL,
  `Address` NVARCHAR(50) NOT NULL,
  `Email` NVARCHAR(50) NOT NULL,
  `License` NVARCHAR(50) NOT NULL,
  PRIMARY KEY (`Supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Product` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Product` (
  `Product_id` INT NOT NULL,
  `Product_name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Manufacture_date` DATE NOT NULL,
  `Expiry_date` DATE NOT NULL,
  `Quantity` INT NOT NULL,
  `Selling_price` INT NOT NULL,
  `Cost_price` VARCHAR(45) NOT NULL,
  `Supplier_id` INT NOT NULL,
  PRIMARY KEY (`Product_id`),
  INDEX `Manufacturer_id_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `Supplier_id`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `db_pharmacy`.`Supplier` (`Supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Sales_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Sales_order` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Sales_order` (
  `Sales_order_id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Cust_name` VARCHAR(45) NOT NULL,
  `Cust_address` VARCHAR(45) NOT NULL,
  `Cust_email` NVARCHAR(50) NOT NULL,
  `Cust_Phn` INT(20) NOT NULL,
  `Status` TINYINT NOT NULL,
  `Total_amount` VARCHAR(45) NOT NULL,
  `Seller_id` INT NOT NULL,
  PRIMARY KEY (`Sales_order_id`),
  INDEX `Seller_id_idx` (`Seller_id` ASC) VISIBLE,
  CONSTRAINT `Seller_id`
    FOREIGN KEY (`Seller_id`)
    REFERENCES `db_pharmacy`.`Seller` (`Seller_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Purchase_order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Purchase_order` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Purchase_order` (
  `Purchase_order_id` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Status` VARCHAR(50) NOT NULL,
  `Total_amount` INT NOT NULL,
  `Supplier_id` INT NOT NULL,
  PRIMARY KEY (`Purchase_order_id`),
  INDEX `Supplier_id_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `Supplier_id`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `db_pharmacy`.`Supplier` (`Supplier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_pharmacy`.`Order_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_pharmacy`.`Order_details` ;

CREATE TABLE IF NOT EXISTS `db_pharmacy`.`Order_details` (
  `Order_detail_id` INT NOT NULL,
  `Quantity` NVARCHAR(50) NOT NULL,
  `Sales_order_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `Purchase_order_id` INT NOT NULL,
  PRIMARY KEY (`Order_detail_id`),
  INDEX `Product_id_idx` (`Product_id` ASC) VISIBLE,
  INDEX `Sales_order_id_idx` (`Sales_order_id` ASC) VISIBLE,
  INDEX `Purchase_order_id_idx` (`Purchase_order_id` ASC) VISIBLE,
  CONSTRAINT `Sales_order_id`
    FOREIGN KEY (`Sales_order_id`)
    REFERENCES `db_pharmacy`.`Sales_order` (`Sales_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Product_id`
    FOREIGN KEY (`Product_id`)
    REFERENCES `db_pharmacy`.`Product` (`Product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Purchase_order_id`
    FOREIGN KEY (`Purchase_order_id`)
    REFERENCES `db_pharmacy`.`Purchase_order` (`Purchase_order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
